export enum PrimeTrustDataType {
  accountCashTotals = "account-cash-totals",
  accountCashTransfers = "account-cash-transfers",
  accounts = "accounts",
  amlChecks = "aml-checks",
  assetContributions = "asset-contributions",
  assetDisbursements = "asset-disbursements",
  assetTransferMethods = "asset-transfer-methods",
  assetTransfers = "asset-transfers",
  authorizationGroups = "authorization-groups",
  banks = "banks",
  cashTransactions = "cash-transactions",
  cipChecks = "cip-checks",
  contactFundsTransferReferences = "contact-funds-transfer-references",
  contacts = "contacts",
  contingentHolds = "contingent-holds",
  contributions = "contributions",
  creditCardResource = "credit-card-resource",
  disbursementAuthorizations = "disbursement-authorizations",
  disbursements = "disbursements",
  fundsTransferMethods = "funds-transfer-methods",
  fundsTransfers = "funds-transfers",
  internalAssetTransfers = "internal-asset-transfers",
  kycDocumentChecks = "kyc-document-checks",
  rules = "rules",
  uploadedDocuments = "uploaded-documents",
  users = "users",
}
