import type { RawAccount } from "../interfaces/account.js";
import type { RawAccountAggregatePolicies } from "../interfaces/account-aggregate-policies.js";
import type { RawAccountAssetTotal } from "../interfaces/account-asset-total.js";
import type { RawAccountCashTotal } from "../interfaces/account-cash-total.js";
import type { RawAccountCashTransfer } from "../interfaces/account-cash-transfer.js";
import type { RawAccountPolicies } from "../interfaces/account-policies.js";
import type { RawAccountQuestionnaire } from "../interfaces/account-questionnaire.js";
import type { RawAccountStatement } from "../interfaces/account-statement.js";
import type { RawAccountSubType } from "../interfaces/account-sub-type.js";
import type { RawAccountTransferAuthorization } from "../interfaces/account-transfer-authorization.js";
import type { RawAccountType } from "../interfaces/account-type.js";
import type { RawAchOriginator } from "../interfaces/ach-originator.js";
import type { RawAchReturn } from "../interfaces/ach-return.js";
import type { RawAddress } from "../interfaces/address.js";
import type { RawAdvancedFilter } from "../interfaces/advanced-filter.js";
import type { RawAmlCheck } from "../interfaces/aml-check.js";
import type { RawAsset } from "../interfaces/asset.js";
import type { RawAssetContribution } from "../interfaces/asset-contribution.js";
import type { RawAssetDisbursement } from "../interfaces/asset-disbursement.js";
import type { RawAssetTransaction } from "../interfaces/asset-transaction.js";
import type { RawAssetTransactionTaxLot } from "../interfaces/asset-transaction-tax-lot.js";
import type { RawAssetTransfer } from "../interfaces/asset-transfer.js";
import type { RawAssetTransferMethod } from "../interfaces/asset-transfer-method.js";
import type { RawAuthorizationGroup } from "../interfaces/authorization-group.js";
import type { RawAuthorizationItem } from "../interfaces/authorization-item.js";
import type { RawAuthorizationRuleGroup } from "../interfaces/authorization-rule-group.js";
import type { RawBalanceCheck } from "../interfaces/balance-check.js";
import type { RawBank } from "../interfaces/bank.js";
import type { RawBrokerAccountAuthorization } from "../interfaces/broker-account-authorization.js";
import type { RawCashTransaction } from "../interfaces/cash-transaction.js";
import type { RawChargeback } from "../interfaces/chargeback.js";
import type { RawCipCheck } from "../interfaces/cip-check.js";
import type { RawContact } from "../interfaces/contact.js";
import type { RawContactBeneficiaries } from "../interfaces/contact-beneficiaries.js";
import type { RawContactFundsTransferReference } from "../interfaces/contact-funds-transfer-reference.js";
import type { RawContactRelationship } from "../interfaces/contact-relationship.js";
import type { RawContingentHold } from "../interfaces/contingent-hold.js";
import type { RawContribution } from "../interfaces/contribution.js";
import type { RawCountries } from "../interfaces/countries.js";
import type { RawCreditCardAuthorization } from "../interfaces/credit-card-authorization.js";
import type { RawCreditCardFailure } from "../interfaces/credit-card-failure.js";
import type { RawCreditCardResource } from "../interfaces/credit-card-resource.js";
import type { RawCustodian } from "../interfaces/custodian.js";
import type { RawDisbursementAuthorization } from "../interfaces/disbursement-authorization.js";
import type { RawDisbursement } from "../interfaces/disbursements.js";
import type { RawElectronicSignature } from "../interfaces/electronic-signature.js";
import type { RawFedwireDetail } from "../interfaces/fedwire-detail.js";
import type { RawFreezeActionItem } from "../interfaces/freeze-action-item.js";
import type { RawFundsTransfer } from "../interfaces/funds-transfer.js";
import type { RawFundsTransferMethod } from "../interfaces/funds-transfer-method.js";
import type { RawHold } from "../interfaces/hold.js";
import type { RawInternalAssetTransfer } from "../interfaces/internal-asset-transfer.js";
import type { RawInternalAssetTransferReview } from "../interfaces/internal-asset-transfer-review.js";
import type { RawIraDistribution } from "../interfaces/ira-distribution.js";
import type { RawIraTransferInForm } from "../interfaces/ira-transfer-in-form.js";
import type { RawKycActionItem } from "../interfaces/kyc-action-item.js";
import type { RawKycDocumentCheck } from "../interfaces/kyc-document-check.js";
import type { RawNocCorrection } from "../interfaces/noc-correction.js";
import type { RawOrganization } from "../interfaces/organization.js";
import type { RawOrganizationDocument } from "../interfaces/organization-document.js";
import type { RawPhoneNumber } from "../interfaces/phone-number.js";
import type { RawPlaidItem } from "../interfaces/plaid-item.js";
import type { RawPushTransferMethod } from "../interfaces/push-transfer-method.js";
import type { RawQuote } from "../interfaces/quote.js";
import type { RawRefund } from "../interfaces/refund.js";
import type { RawResourceToken } from "../interfaces/resource-token.js";
import type { RawRule } from "../interfaces/rule.js";
import type { RawTokenAsset } from "../interfaces/token-asset.js";
import type { RawTrade } from "../interfaces/trade.js";
import type { RawTradeSettlement } from "../interfaces/trade-settlement.js";
import type { RawTradeSettlementConfig } from "../interfaces/trade-settlement-config.js";
import type { RawUiLog } from "../interfaces/ui-log.js";
import type { RawUploadedDocument } from "../interfaces/uploaded-document.js";
import type { RawUser } from "../interfaces/user.js";
import type { RawUserGroup } from "../interfaces/user-group.js";
import type { RawUserInvitation } from "../interfaces/user-invitation.js";
import type { RawWebhook } from "../interfaces/webhook.js";
import type { RawWebhookConfig } from "../interfaces/webhook-config.js";
import type { RawWireInitiator } from "../interfaces/wire-initiator.js";
import type { PrimeTrustDataType } from "./enum/pt-data-type.js";

export interface RawMap {
  [PrimeTrustDataType.chargebacks]: RawChargeback;
  [PrimeTrustDataType.accountAggregatePolicies]: RawAccountAggregatePolicies;
  [PrimeTrustDataType.accountCashTotals]: RawAccountCashTotal;
  [PrimeTrustDataType.accountCashTransfers]: RawAccountCashTransfer;
  [PrimeTrustDataType.accountPolicies]: RawAccountPolicies;
  [PrimeTrustDataType.accountAssetTotals]: RawAccountAssetTotal;
  [PrimeTrustDataType.accountQuestionnaires]: RawAccountQuestionnaire;
  [PrimeTrustDataType.accountStatements]: RawAccountStatement;
  [PrimeTrustDataType.accountSubTypes]: RawAccountSubType;
  [PrimeTrustDataType.accountTransferAuthorizations]: RawAccountTransferAuthorization;
  [PrimeTrustDataType.addresses]: RawAddress;
  [PrimeTrustDataType.accountTypes]: RawAccountType;
  [PrimeTrustDataType.accounts]: RawAccount;
  [PrimeTrustDataType.achOriginators]: RawAchOriginator;
  [PrimeTrustDataType.achReturns]: RawAchReturn;
  [PrimeTrustDataType.advancedFilters]: RawAdvancedFilter;
  [PrimeTrustDataType.amlChecks]: RawAmlCheck;
  [PrimeTrustDataType.assetContributions]: RawAssetContribution;
  [PrimeTrustDataType.assetDisbursements]: RawAssetDisbursement;
  [PrimeTrustDataType.assetTransactionTaxLots]: RawAssetTransactionTaxLot;
  [PrimeTrustDataType.assetTransactions]: RawAssetTransaction;
  [PrimeTrustDataType.assetTransferMethods]: RawAssetTransferMethod;
  [PrimeTrustDataType.assetTransfers]: RawAssetTransfer;
  [PrimeTrustDataType.assets]: RawAsset;
  [PrimeTrustDataType.authorizationGroups]: RawAuthorizationGroup;
  [PrimeTrustDataType.authorizationItems]: RawAuthorizationItem;
  [PrimeTrustDataType.authorizationRuleGroups]: RawAuthorizationRuleGroup;
  [PrimeTrustDataType.balanceChecks]: RawBalanceCheck;
  [PrimeTrustDataType.banks]: RawBank;
  [PrimeTrustDataType.brokerAccountAuthorizations]: RawBrokerAccountAuthorization;
  [PrimeTrustDataType.cashTransactions]: RawCashTransaction;
  [PrimeTrustDataType.cipChecks]: RawCipCheck;
  [PrimeTrustDataType.contactBeneficiaries]: RawContactBeneficiaries;
  [PrimeTrustDataType.contactFundsTransferReferences]: RawContactFundsTransferReference;
  [PrimeTrustDataType.contactRelationships]: RawContactRelationship;
  [PrimeTrustDataType.contacts]: RawContact;
  [PrimeTrustDataType.contingentHolds]: RawContingentHold;
  [PrimeTrustDataType.contributions]: RawContribution;
  [PrimeTrustDataType.countries]: RawCountries;
  [PrimeTrustDataType.creditCardAuthorizations]: RawCreditCardAuthorization;
  [PrimeTrustDataType.creditCardFailures]: RawCreditCardFailure;
  [PrimeTrustDataType.creditCardResources]: RawCreditCardResource;
  [PrimeTrustDataType.custodians]: RawCustodian;
  [PrimeTrustDataType.disbursementAuthorizations]: RawDisbursementAuthorization;
  [PrimeTrustDataType.disbursements]: RawDisbursement;
  [PrimeTrustDataType.electronicSignatures]: RawElectronicSignature;
  [PrimeTrustDataType.fedwireDetails]: RawFedwireDetail;
  [PrimeTrustDataType.freezeActionItems]: RawFreezeActionItem;
  [PrimeTrustDataType.fundsTransferMethods]: RawFundsTransferMethod;
  [PrimeTrustDataType.fundsTransfers]: RawFundsTransfer;
  [PrimeTrustDataType.holds]: RawHold;
  [PrimeTrustDataType.internalAssetTransferReviews]: RawInternalAssetTransferReview;
  [PrimeTrustDataType.internalAssetTransfers]: RawInternalAssetTransfer;
  [PrimeTrustDataType.iraDistributions]: RawIraDistribution;
  [PrimeTrustDataType.iraTransferInForms]: RawIraTransferInForm;
  [PrimeTrustDataType.kycActionItems]: RawKycActionItem;
  [PrimeTrustDataType.kycDocumentChecks]: RawKycDocumentCheck;
  [PrimeTrustDataType.quotes]: RawQuote;
  [PrimeTrustDataType.nocCorrections]: RawNocCorrection;
  [PrimeTrustDataType.organizationDocuments]: RawOrganizationDocument;
  [PrimeTrustDataType.organizations]: RawOrganization;
  [PrimeTrustDataType.phoneNumbers]: RawPhoneNumber;
  [PrimeTrustDataType.plaidItems]: RawPlaidItem;
  [PrimeTrustDataType.pushTransferMethods]: RawPushTransferMethod;
  [PrimeTrustDataType.refunds]: RawRefund;
  [PrimeTrustDataType.resourceTokens]: RawResourceToken;
  [PrimeTrustDataType.rules]: RawRule;
  [PrimeTrustDataType.tokenAssets]: RawTokenAsset;
  [PrimeTrustDataType.tradeSettlementConfigs]: RawTradeSettlementConfig;
  [PrimeTrustDataType.tradeSettlements]: RawTradeSettlement;
  [PrimeTrustDataType.trades]: RawTrade;
  [PrimeTrustDataType.uiLogs]: RawUiLog;
  [PrimeTrustDataType.uploadedDocuments]: RawUploadedDocument;
  [PrimeTrustDataType.userGroups]: RawUserGroup;
  [PrimeTrustDataType.userInvitations]: RawUserInvitation;
  [PrimeTrustDataType.users]: RawUser;
  [PrimeTrustDataType.webhookConfigs]: RawWebhookConfig;
  [PrimeTrustDataType.webhooks]: RawWebhook;
  [PrimeTrustDataType.wireInitiators]: RawWireInitiator;
}
