export interface RawFundsTransferMethod {
  achCheckType: string | null;
  bankAccountName: string;
  bankAccountType: string;
  bankName: string | null;
  checkPayee: string | null;
  contactEmail: string;
  contactName: string;
  creditCardBin: string | null;
  creditCardExpirationDate: string | null;
  creditCardFundingType: string | null;
  creditCardName: string | null;
  creditCardPostalCode: string | null;
  creditCardType: string | null;
  disbursementApproved: boolean;
  etPaymentMethodId: string | null;
  fingerprint: string;
  fundsTransferType: string;
  furtherCreditAccountName: string | null;
  furtherCreditAccountNumber: string | null;
  iban: string | null;
  inactive: boolean;
  intermediaryBankName: string | null;
  intermediaryBankReference: string | null;
  intermediaryBankRoutingNumber: string | null;
  intermediaryBankSwiftCode: string | null;
  ipAddress: string | null;
  label: string | null;
  last4: string;
  routingNumber: string;
  signetAddress: string | null;
  swiftCode: string | null;
}
